name: Build

on:
    - workflow_dispatch
    - push

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.9
          #- 3.11
          #- jim-3.9-fix-integration
        os:
          - ubuntu-latest
          # - windows-latest
          - windows-2019
          #- macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Nuitka/Nuitka-Python.git
          #repository: jimkring/Nuitka-Python.git
          ref: ${{matrix.version}}

      - if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 16.11
          # vsversion: 2019

      - if: runner.os == 'Windows'
        run: |
          &"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          .\build.bat

      - if: runner.os == 'Linux'
        run: |
          ./build.sh
          mkdir output && tar -czf output/nuitka-python39.tar.gz /opt/nuitka-python39

      - if: runner.os == 'macOS'
        run: ./build.mac.sh

      - if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.version}}-${{matrix.os}}
          path: output

      - if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.version}}-${{matrix.os}}
          path: /opt/nuitka-python39/bin
