name: Build

on:
    - workflow_dispatch
    - push

jobs:
  Build:
    strategy:
      matrix:
        version:
          - 3.9
          # - 3.11
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          # repository: Nuitka/Nuitka-Python.git
          repository: jimkring/Nuitka-Python.git
          ref: 3.9
      - if: runner.os == 'Windows'
        run: .\build.bat
      - if: runner.os == 'Linux'
        run: ./build.sh
      - if: runner.os == 'macOS'
        run: ./build.mac.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.version}}-${{matrix.os}}
          path: output
